import React, { useState } from 'react'
import { ChevronLeft, ChevronRight, Quote } from 'lucide-react'

const testimonials = [
  {
    quote:
      "Udyo360 found 23 critical SQL injection vulnerabilities in our payment processing API that our previous scanner completely missed. The CVSS-scored report made prioritization effortless — our devs had patches deployed within 48 hours.",
    name: 'Sarah Mitchell',
    title: 'VP of Application Security',
    company: 'FinTech Global',
    initials: 'SM',
    color: 'bg-blue-600',
  },
  {
    quote:
      "We integrated Udyo360 into our GitHub Actions pipeline in under an hour. Now every PR gets scanned automatically and developers get inline fix suggestions. Our vulnerability backlog has dropped by 70% in three months.",
    name: 'Raj Patel',
    title: 'Head of DevSecOps',
    company: 'CloudNative Inc.',
    initials: 'RP',
    color: 'bg-purple-600',
  },
  {
    quote:
      "The OWASP Top 10 compliance report generated by Udyo360 was instrumental in passing our PCI-DSS audit. The auditors were impressed by the depth of coverage and the clear remediation guidance.",
    name: 'Elena Vasquez',
    title: 'CISO',
    company: 'RetailChain Corp',
    initials: 'EV',
    color: 'bg-teal-600',
  },
  {
    quote:
      "As a penetration tester, Udyo360 handles the tedious recon and automated checks so I can spend my time on business logic flaws and complex exploit chains. It's added two billable hours per engagement.",
    name: 'James O\'Brien',
    title: 'Senior Penetration Tester',
    company: 'SecureForce Ltd.',
    initials: 'JO',
    color: 'bg-orange-600',
  },
]

export default function Testimonials() {
  const [current, setCurrent] = useState(0)

  const prev = () => setCurrent((c) => (c - 1 + testimonials.length) % testimonials.length)
  const next = () => setCurrent((c) => (c + 1) % testimonials.length)

  const t = testimonials[current]

  return (
    <section className="py-20 md:py-28 bg-navy-900 relative overflow-hidden">
      <div className="absolute inset-0 grid-bg opacity-20" />
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-px h-full bg-gradient-to-b from-transparent via-white/10 to-transparent" />

      <div className="relative max-w-4xl mx-auto px-4 sm:px-6 text-center">
        <span className="section-tag text-crimson-400">Customer Stories</span>
        <h2 className="text-3xl md:text-4xl font-bold text-white mb-14">
          Trusted by Security Professionals Worldwide
        </h2>

        <div className="relative bg-white/5 border border-white/10 rounded-2xl p-8 md:p-12 backdrop-blur-sm">
          {/* Quote icon */}
          <Quote className="w-10 h-10 text-crimson-500/40 mx-auto mb-6" />

          <p className="text-lg md:text-xl text-gray-200 leading-relaxed italic mb-8">
            "{t.quote}"
          </p>

          <div className="flex items-center justify-center gap-4">
            <div className={`w-12 h-12 ${t.color} rounded-full flex items-center justify-center text-white font-bold text-sm shrink-0`}>
              {t.initials}
            </div>
            <div className="text-left">
              <div className="text-white font-semibold">{t.name}</div>
              <div className="text-gray-400 text-sm">{t.title}, {t.company}</div>
            </div>
          </div>
        </div>

        {/* Navigation */}
        <div className="flex items-center justify-center gap-4 mt-8">
          <button
            onClick={prev}
            className="w-10 h-10 rounded-full border border-white/20 flex items-center justify-center text-white hover:bg-white/10 transition-colors"
          >
            <ChevronLeft className="w-5 h-5" />
          </button>

          <div className="flex gap-2">
            {testimonials.map((_, i) => (
              <button
                key={i}
                onClick={() => setCurrent(i)}
                className={`w-2 h-2 rounded-full transition-all duration-300 ${
                  i === current ? 'bg-crimson-500 w-6' : 'bg-white/30'
                }`}
              />
            ))}
          </div>

          <button
            onClick={next}
            className="w-10 h-10 rounded-full border border-white/20 flex items-center justify-center text-white hover:bg-white/10 transition-colors"
          >
            <ChevronRight className="w-5 h-5" />
          </button>
        </div>
      </div>
    </section>
  )
}
